/**
 * Narrative Builder Service
 * 
 * Transforms ExecutionStory (event-focused) into ExecutionNarrative (intent-focused).
 * 
 * Process:
 * 1. Extract business domains from component/service names
 * 2. Cluster execution steps by domain
 * 3. Create chapters with aggregated metrics
 * 4. Detect causality between chapters
 * 5. Generate chapter-level insights
 */

import { Injectable } from '@angular/core';
import type {
  ExecutionStory,
  ExecutionStep,
  ImpactMetrics,
  InsightMessage,
  ExecutionScore,
} from '../../../../types/execution-intelligence';
import type {
  ExecutionNarrative,
  Chapter,
  Subsection,
  BusinessDomain,
  ChapterMetrics,
  ChapterChange,
  NarrativeBuilderConfig,
} from '../../../../types/execution-narrative';
import { DEFAULT_DOMAIN_KEYWORDS, DEFAULT_DOMAIN_ICONS, DEFAULT_NARRATIVE_CONFIG } from '../../../../types/execution-narrative';

@Injectable({
  providedIn: 'root',
})
export class NarrativeBuilderService {
  private config: NarrativeBuilderConfig = DEFAULT_NARRATIVE_CONFIG;

  /**
   * Transform ExecutionStory into ExecutionNarrative.
   */
  buildNarrative(story: ExecutionStory): ExecutionNarrative {
    // Step 1: Extract business domains from all component/service/API names
    const domains = this.extractDomains(story);

    // Step 2: Cluster steps by domain
    const stepsByDomain = this.clusterStepsByDomain(story.steps, domains);

    // Step 3: Create chapters from clusters
    const chapters = this.createChapters(story, stepsByDomain, domains);

    // Step 4: Detect causality between chapters
    this.detectChapterCausality(chapters);

    // Step 5: Generate chapter insights
    chapters.forEach(chapter => {
      this.generateChapterInsights(chapter);
    });

    // Step 6: Aggregate metrics
    const metrics = this.aggregateMetrics(chapters);

    // Create narrative
    const narrative: ExecutionNarrative = {
      id: `narrative-${story.id}`,
      storyId: story.id,
      title: story.title,
      trigger: this.extractTrigger(story),
      startTime: story.startTime,
      endTime: story.endTime,
      duration: story.duration,
      chapters,
      chapterCount: chapters.length,
      executionNarrative: '', // Will be generated by ExecutionNarrativeGeneratorService
      metrics,
      observations: this.generateObservations(chapters, story.insights),
      executionScore: story.executionScore,
      insights: story.insights,
      originalStory: story,
    };

    return narrative;
  }

  /**
   * Extract business domains from component/service/API names.
   */
  private extractDomains(story: ExecutionStory): BusinessDomain[] {
    const domainMap = new Map<string, Set<string>>();

    // Collect all names from steps
    story.steps.forEach(step => {
      step.eventIds.forEach(eventId => {
        const event = step.events?.[0]; // Simplified - use first event
        if (!event) return;

        if (event.sourceComponent) {
          this.extractDomainsFromName(event.sourceComponent, domainMap);
        }
        if (event.ownerClass) {
          this.extractDomainsFromName(event.ownerClass, domainMap);
        }
        if (event.label) {
          this.extractDomainsFromName(event.label, domainMap);
        }
      });
    });

    // Convert map to domain objects
    const domains: BusinessDomain[] = [];
    domainMap.forEach((components, domainName) => {
      domains.push({
        id: domainName.toLowerCase(),
        name: domainName,
        icon: this.config.domainIcons[domainName] || '📌',
        componentNames: Array.from(components),
        serviceNames: [],
        apiEndpoints: [],
        confidence: 0.8,
      });
    });

    return domains;
  }

  /**
   * Extract domain name from a component/service name.
   * Examples:
   * - "RevenueChart" → "Revenue"
   * - "_OrdersDataGrid" → "Orders"
   * - "UserProfileService" → "User"
   */
  private extractDomainsFromName(name: string, domainMap: Map<string, Set<string>>): void {
    // Remove common suffixes
    let cleaned = name
      .replace(/^_/, '') // Remove leading underscore
      .replace(/(Component|Service|Store|Guard|Interceptor|Pipe|Directive)$/, '')
      .replace(/API$/, '');

    // Try to match against known keywords
    for (const [domain, keywords] of Object.entries(this.config.domainKeywords)) {
      for (const keyword of keywords) {
        if (cleaned.toLowerCase().includes(keyword.toLowerCase())) {
          if (!domainMap.has(domain)) {
            domainMap.set(domain, new Set());
          }
          domainMap.get(domain)!.add(name);
          return;
        }
      }
    }

    // If no keyword match, try to extract first word (PascalCase)
    const match = cleaned.match(/^([A-Z][a-z]+)/);
    if (match) {
      const domain = match[1];
      if (!domainMap.has(domain)) {
        domainMap.set(domain, new Set());
      }
      domainMap.get(domain)!.add(name);
    }
  }

  /**
   * Cluster execution steps by business domain.
   */
  private clusterStepsByDomain(
    steps: ExecutionStep[],
    domains: BusinessDomain[]
  ): Map<string, ExecutionStep[]> {
    const clusters = new Map<string, ExecutionStep[]>();

    steps.forEach(step => {
      // Find which domain this step belongs to
      let assignedDomain: string | null = null;

      for (const domain of domains) {
        // Check if step title or events mention this domain
        if (step.title.toLowerCase().includes(domain.name.toLowerCase())) {
          assignedDomain = domain.id;
          break;
        }

        // Check event details
        if (step.events) {
          for (const event of step.events) {
            if (
              event.label?.toLowerCase().includes(domain.name.toLowerCase()) ||
              event.sourceComponent?.toLowerCase().includes(domain.name.toLowerCase())
            ) {
              assignedDomain = domain.id;
              break;
            }
          }
        }

        if (assignedDomain) break;
      }

      // Default to "General" if no domain matched
      if (!assignedDomain) {
        assignedDomain = 'general';
      }

      if (!clusters.has(assignedDomain)) {
        clusters.set(assignedDomain, []);
      }
      clusters.get(assignedDomain)!.push(step);
    });

    return clusters;
  }

  /**
   * Create chapters from step clusters.
   */
  private createChapters(
    story: ExecutionStory,
    stepsByDomain: Map<string, ExecutionStep[]>,
    domains: BusinessDomain[]
  ): Chapter[] {
    const chapters: Chapter[] = [];
    let sequenceNumber = 1;

    // Get domain map for quick lookup
    const domainMap = new Map(domains.map(d => [d.id, d]));

    stepsByDomain.forEach((steps, domainId) => {
      const domain = domainMap.get(domainId) || this.createDefaultDomain(domainId);

      // Aggregate steps in this domain
      const startTime = Math.min(...steps.map(s => s.startTime));
      const endTime = Math.max(...steps.map(s => s.endTime));
      const duration = endTime - startTime;

      // Create subsections from steps
      const subsections = steps.map((step, idx) =>
        this.createSubsectionFromStep(step, idx, domain)
      );

      // Create chapter
      const chapter: Chapter = {
        id: `chapter-${domainId}-${sequenceNumber}`,
        domain,
        sequenceNumber: sequenceNumber++,
        summary: this.generateChapterSummary(steps, domain),
        duration,
        startTime,
        endTime,
        stepIds: steps.map(s => s.id),
        metrics: this.aggregateChapterMetrics(steps),
        causedBy: null,
        triggers: [],
        trigger: this.extractTrigger(story),
        changes: this.extractChapterChanges(steps),
        affectedComponents: this.extractAffectedComponents(steps),
        subsections,
        observations: [],
      };

      chapters.push(chapter);
    });

    // Sort by start time
    chapters.sort((a, b) => a.startTime - b.startTime);

    // Re-number sequences after sort
    chapters.forEach((ch, idx) => {
      ch.sequenceNumber = idx + 1;
    });

    return chapters;
  }

  /**
   * Create a subsection from an execution step.
   */
  private createSubsectionFromStep(step: ExecutionStep, index: number, domain: BusinessDomain): Subsection {
    const typeToIcon: Record<string, string> = {
      'data-fetch': '🌐',
      'state-update': '💾',
      'ui-update': '🎨',
      'computation': '⚡',
      'user-interaction': '👆',
      'navigation': '🧭',
      'background-task': '⏳',
      'error-handling': '⚠️',
      'validation': '✓',
    };

    return {
      id: `subsection-${step.id}`,
      type: step.type as 'api' | 'store' | 'signal' | 'component' | 'render' | 'computed',
      label: step.title,
      icon: typeToIcon[step.type] || '📌',
      summary: step.summary,
      implementation: step.title || '',
      duration: step.duration,
      changes: this.extractChapterChanges([step]),
      causedBy: index > 0 ? `subsection-${step.id}` : domain.name,
      triggers: [],
      consumers: step.impact.components.names || [],
      observations: step.stepInsights?.map(i => i.description) || [],
    };
  }

  /**
   * Generate summary for a chapter.
   */
  private generateChapterSummary(steps: ExecutionStep[], domain: BusinessDomain): string {
    const actionTypes = new Set(steps.map(s => s.type));

    if (actionTypes.has('data-fetch')) {
      return `Loaded ${domain.name} data from API`;
    } else if (actionTypes.has('state-update')) {
      return `Updated ${domain.name} state`;
    } else if (actionTypes.has('ui-update')) {
      return `Updated ${domain.name} UI`;
    }

    return `Processed ${domain.name}`;
  }

  /**
   * Aggregate metrics for a chapter from its steps.
   */
  private aggregateChapterMetrics(steps: ExecutionStep[]): ChapterMetrics {
    let totalApiDuration = 0;
    let apiCount = 0;
    let apiEndpoints: string[] = [];

    let storeCount = 0;
    let storeNames: string[] = [];
    let propertiesChanged = 0;

    let signalCount = 0;
    let signalNames: string[] = [];

    let componentCount = 0;
    let componentNames: string[] = [];
    let renderDuration = 0;
    let slowRenders = 0;

    let payloadSize = 0;

    steps.forEach(step => {
      // Count by type
      if (step.type === 'data-fetch') {
        apiCount++;
        totalApiDuration += step.duration;
        apiEndpoints.push(step.title);
      } else if (step.type === 'state-update') {
        storeCount++;
        storeNames.push(step.title);
        propertiesChanged += step.changes.added.count + step.changes.modified.count;
      } else if (step.type === 'computation') {
        signalCount++;
        signalNames.push(step.title);
      } else if (step.type === 'ui-update') {
        componentCount++;
        componentNames.push(step.title);
        renderDuration += step.duration;
        if (step.duration > 16) slowRenders++;
      }

      // Estimate payload from diff
      if (step.changes.beforeSnapshot) {
        payloadSize += JSON.stringify(step.changes.beforeSnapshot).length;
      }
    });

    return {
      apiCalls: {
        count: apiCount,
        endpoints: apiEndpoints,
        totalDuration: totalApiDuration,
        failures: 0,
      },
      storeUpdates: {
        count: storeCount,
        storeNames,
        propertiesChanged,
      },
      signalEmissions: {
        count: signalCount,
        signalNames,
      },
      componentRenders: {
        count: componentCount,
        componentNames,
        totalDuration: renderDuration,
        slowRenders,
      },
      payloadSize,
      payloadGrowth: 0,
    };
  }

  /**
   * Extract data changes from steps.
   */
  private extractChapterChanges(steps: ExecutionStep[]): ChapterChange[] {
    const changes: ChapterChange[] = [];

    steps.forEach(step => {
      step.changes.modified.properties.forEach(prop => {
        changes.push({
          entityType: 'Data',
          field: prop.key,
          before: prop.oldValue,
          after: prop.newValue,
          changeType: 'modified',
          humanReadable: `${prop.key}: ${prop.oldValue} → ${prop.newValue}`,
          affectedComponents: step.impact.components.names || [],
        });
      });

      step.changes.added.properties.forEach(prop => {
        changes.push({
          entityType: 'Data',
          field: prop.key,
          before: 'undefined',
          after: prop.value,
          changeType: 'added',
          humanReadable: `${prop.key}: added (${prop.value})`,
          affectedComponents: step.impact.components.names || [],
        });
      });
    });

    return changes;
  }

  /**
   * Extract affected component names.
   */
  private extractAffectedComponents(steps: ExecutionStep[]): string[] {
    const components = new Set<string>();

    steps.forEach(step => {
      step.impact.components.names.forEach(name => components.add(name));
      step.impact.directConsumers.forEach(name => components.add(name));
    });

    return Array.from(components);
  }

  /**
   * Detect causality between chapters.
   */
  private detectChapterCausality(chapters: Chapter[]): void {
    chapters.forEach((chapter, idx) => {
      // Chapter is caused by previous chapter (in sequence)
      if (idx > 0) {
        chapter.causedBy = chapters[idx - 1];
        chapters[idx - 1].triggers.push(chapter);
      }
    });
  }

  /**
   * Generate insights for a chapter.
   */
  private generateChapterInsights(chapter: Chapter): void {
    const observations: string[] = [];

    // Slow rendering
    if (chapter.metrics.componentRenders.slowRenders > 0) {
      observations.push(
        `${chapter.metrics.componentRenders.slowRenders} slow renders (> 16ms) in ${chapter.domain.name}`
      );
    }

    // Large payload
    if (chapter.metrics.payloadSize > 1000000) {
      observations.push(
        `Large payload (${(chapter.metrics.payloadSize / 1000000).toFixed(1)}MB) for ${chapter.domain.name}`
      );
    }

    // Many API calls
    if (chapter.metrics.apiCalls.count > 3) {
      observations.push(`Multiple API calls (${chapter.metrics.apiCalls.count}) in ${chapter.domain.name}`);
    }

    chapter.observations = observations;
  }

  /**
   * Generate observations from all chapters and insights.
   */
  private generateObservations(chapters: Chapter[], insights: InsightMessage[]): string[] {
    const observations: string[] = [];

    // From chapters
    chapters.forEach(ch => {
      observations.push(...ch.observations);
    });

    // From insights
    insights.forEach(insight => {
      if (insight.severity === 'warning' || insight.severity === 'critical') {
        observations.push(insight.description);
      }
    });

    return observations;
  }

  /**
   * Aggregate metrics from all chapters.
   */
  private aggregateMetrics(chapters: Chapter[]) {
    let totalApiCalls = 0;
    let totalComponents = 0;
    let totalRenders = 0;
    let totalPayloadSize = 0;
    let totalSignalEmissions = 0;

    chapters.forEach(ch => {
      totalApiCalls += ch.metrics.apiCalls.count;
      totalComponents += ch.metrics.componentRenders.count;
      totalRenders += ch.metrics.componentRenders.count;
      totalPayloadSize += ch.metrics.payloadSize;
      totalSignalEmissions += ch.metrics.signalEmissions.count;
    });

    return {
      totalApiCalls,
      totalComponents,
      totalRenders,
      totalPayloadSize,
      totalSignalEmissions,
    };
  }

  /**
   * Extract user intent/trigger that started this story.
   */
  private extractTrigger(story: ExecutionStory | { steps?: ExecutionStep[] }): string {
    if (!('steps' in story) || !story.steps || story.steps.length === 0) {
      return 'User action';
    }

    const firstStep = story.steps[0];
    if (firstStep?.events && firstStep.events.length > 0) {
      const event = firstStep.events[0];
      return event.label || 'User action';
    }

    return firstStep?.title || 'User action';
  }

  /**
   * Create a default domain object.
   */
  private createDefaultDomain(id: string): BusinessDomain {
    return {
      id,
      name: id.charAt(0).toUpperCase() + id.slice(1),
      icon: '📌',
      componentNames: [],
      serviceNames: [],
      apiEndpoints: [],
      confidence: 0.5,
    };
  }
}
